#pragma once
#define IBEX_ENCRYPTION_SUCCESS							0
#define IBEX_ENCRYPTION_BASE							10000
#define IBEX_ENCRYPTION_BUFFER_EMPTY					IBEX_ENCRYPTION_BASE + 1
#define IBEX_ENCRYPTION_KEY_INVALID						IBEX_ENCRYPTION_BASE + 2
#define IBEX_ENCRYPTION_FILE_EMPTY						IBEX_ENCRYPTION_BASE + 3
#define IBEX_ENCRYPTION_FILE_OPEN_FAILED				IBEX_ENCRYPTION_BASE + 4
#define IBEX_ENCRYPTION_INIT_FAILED						IBEX_ENCRYPTION_BASE + 5
#define IBEX_ENCRYPTION_UPDATE_FAILED					IBEX_ENCRYPTION_BASE + 6
#define IBEX_ENCRYPTION_FINAL_FAILED					IBEX_ENCRYPTION_BASE + 7
#define IBEX_ENCRYPTION_EXCEPTION						IBEX_ENCRYPTION_BASE + 8
